#!/bin/bash

#export USER="xavier666"
#export HOME="/home/$USER"
export SCRIPT_DIR="$HOME/Documents/scripts_dir/standalone"

sxhkd &

$SCRIPT_DIR/monitor_toggle 2
$HOME/.config/picom/launch.sh
$HOME/.config/dunst/launch.sh
$HOME/.config/polybar/launch.sh
nitrogen --restore

bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor eDP-1  -d 5 6 7 8
bspc monitor eDP-1 -s HDMI-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
