#!/bin/bash

export SCRIPT_DIR="$HOME/Documents/scripts_dir/standalone"
export TERMINAL="alacritty"
export BROWSER="firefox"
export FILE_MANAGER="thunar"
export SXHKD_SCRIPT_DIR="$HOME/Documents/scripts_dir"
export SXHKD_CONFIG_DIR="$HOME/.config"

$SCRIPT_DIR/monitor_toggle 0
$HOME/.config/picom/launch.sh
$HOME/.config/dunst/launch.sh
$HOME/.config/polybar/launch.sh
nitrogen --restore

sxhkd -c ~/.config/sxhkd/config_bspwm ~/.config/sxhkd/config_common &

bspc monitor HDMI-1 -d 1 2 3 4 9 10
bspc monitor eDP-1 -d 5 6 7 8
bspc monitor eDP-1 -s HDMI-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
